Added Join Organization Issue Template
nhcommunity/community pull request #7
Opened 2021-07-29 09:37 UTC by prathamesh-borse

# Pull Request
This pull request closes an issue related to the get involved beginners who wish to contribute to this community.

## Description:
This pull request is made for adding the issue template that is related to adding newcomers or beginners to the community.

## Related Issue:

Closes #4

2021-07-29 15:35 UTC, nhcarrigan requested changes
This is looking good. Just some small tweaks.

2021-07-29 15:35 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/join_org.yml
> +assignees: prathamesh-borse
```suggestion
assignees: nhcarrigan
```
This should be me 🙂

2021-07-29 15:35 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/join_org.yml
> +      required: true
```suggestion
      required: true

```
Need a new line at the end of the file.

2021-07-29 15:35 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/join_org.yml
> +      value: '# Join Organization'
```suggestion
      value: '# Join Our Organization'
```
Just a nitpick.

2021-07-29 15:35 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/join_org.yml
> +      label: Please Explain why do you want to join the organization?
```suggestion
      label: Why do you want to join our organization? 
```

2021-07-29 15:35 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/join_org.yml
> +        Include the steps you took to cause the bug, and an explanation of what occurred.
```suggestion
      description: Please provide a clear description of why you want to join our organization.
```

2021-07-29 15:35 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/join_org.yml
> +description: This issue template can be helpful for beginner who wish to join the community..
```suggestion
description: Use this template to request an invitation to our organization.
```

2021-07-29 17:48 UTC, Panquesito7 commented on .github/ISSUE_TEMPLATE/join_org.yml
> +title: "Invite me to the organization"
This is just an idea; I'm not sure if it's good, though.

```suggestion
title: "[ORG] Invite me to the organization"
```

2021-07-29 17:48 UTC, Panquesito7 commented on .github/ISSUE_TEMPLATE/join_org.yml
> +    id: joinorgdescription
```suggestion
    id: description
```

2021-07-30 03:59 UTC, nhcarrigan approved these changes
Looks good to me.

2021-07-30 03:59 UTC, merged

2021-07-30 03:59 UTC, nhcarrigan commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

2021-07-30 04:00 UTC, prathamesh-borse commented
@nhcarrigan can I Delete this branch now?

2021-07-30 04:01 UTC, prathamesh-borse commented
and also @nhcarrigan we can close #4 this Now what do you say?

2021-07-30 04:02 UTC, nhcarrigan commented
I intentionally left the issue open so we can continue discussing other potential templates.

2021-07-30 04:04 UTC, prathamesh-borse commented
> I intentionally left the issue open so we can continue discussing other potential templates.

@nhcarrigan can I delete the issue template branch what do you say?

2021-07-30 17:07 UTC, Panquesito7 commented
> can I delete this branch now?

Yes, you can delete the branch safely now. 🙂

2021-07-31 03:27 UTC, prathamesh-borse commented
> > can I delete this branch now?
> 
> Yes, you can delete the branch safely now. 🙂

@Panquesito7 Thanks for Replying! 👍